// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaleManagerApi.Data;

#nullable disable

namespace SaleManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602060255_AddDailyPreTripChecklist")]
    partial class AddDailyPreTripChecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaleManagerApi.Models.Admin", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Right")
                        .HasColumnType("integer")
                        .HasColumnName("right");

                    b.HasKey("Name");

                    b.ToTable("admin");

                    b.HasData(
                        new
                        {
                            Name = "tr",
                            Password = "123123",
                            Right = 1
                        });
                });

            modelBuilder.Entity("SaleManagerApi.Models.DailyPreTripChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecklistData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checklistdata");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("MaLx")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("malx");

                    b.Property<string>("MaNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manvt");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sothe");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennvt");

                    b.HasKey("Id");

                    b.ToTable("dailypretripchecklist");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DangTai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaDangTai")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaVeSinh")
                        .HasColumnType("boolean");

                    b.Property<string>("MaLx")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayDangTai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DangTais");
                });

            modelBuilder.Entity("SaleManagerApi.Models.NhaVanTai", b =>
                {
                    b.Property<string>("MaNvt")
                        .HasColumnType("text")
                        .HasColumnName("manvt");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennvt");

                    b.HasKey("MaNvt");

                    b.ToTable("nhavantai");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SaleManagerApi.Models.PreTripChecklistParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DieuKien")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dieukien");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("noidung");

                    b.Property<int>("Stt")
                        .HasColumnType("integer")
                        .HasColumnName("stt");

                    b.HasKey("Id");

                    b.ToTable("pretripchecklistparam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DieuKien = "Bằng lái xe phù hợp với loại xe điều khiển và còn hạn...",
                            IsActive = true,
                            NoiDung = "Hồ sơ và Nhân viên lái xe",
                            Stt = 1
                        });
                });

            modelBuilder.Entity("SaleManagerApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop Dell XPS 15",
                            Price = 1500.00m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bàn phím cơ Keychron Q1",
                            Price = 150.00m,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("SaleManagerApi.Models.Thenhathau", b =>
                {
                    b.Property<string>("MaLx")
                        .HasColumnType("text")
                        .HasColumnName("malx");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cccd");

                    b.Property<string>("MaNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manvt");

                    b.Property<string>("Sodt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sodt");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sothe");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennvt");

                    b.Property<DateTime>("Thoihanthe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoihanthe");

                    b.HasKey("MaLx");

                    b.ToTable("thenhathau");
                });
#pragma warning restore 612, 618
        }
    }
}
