// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaleManagerApi.Data;

#nullable disable

namespace SaleManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726090900_AddInventoryTables")]
    partial class AddInventoryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaleManagerApi.Models.Admin", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Right")
                        .HasColumnType("integer")
                        .HasColumnName("right");

                    b.HasKey("Name");

                    b.ToTable("admin");

                    b.HasData(
                        new
                        {
                            Name = "tr",
                            Password = "123123",
                            Right = 1
                        });
                });

            modelBuilder.Entity("SaleManagerApi.Models.ChungTuVaoKho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("KhohangId")
                        .HasColumnType("integer")
                        .HasColumnName("khohangid");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lydo");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaydangky");

                    b.Property<string>("SoSTO")
                        .HasColumnType("text")
                        .HasColumnName("sosto");

                    b.Property<string>("SoShipment")
                        .HasColumnType("text")
                        .HasColumnName("soshipment");

                    b.Property<string>("SoTransferOut")
                        .HasColumnType("text")
                        .HasColumnName("sotransferout");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sothe");

                    b.HasKey("Id");

                    b.ToTable("chungtuvaokho");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DailyKiemtravesinhxe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("LanVaoKhoTrongNgay")
                        .HasColumnType("integer")
                        .HasColumnName("lanvaokhotrongngay");

                    b.Property<string>("MaLx")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("malx");

                    b.Property<string>("MaNvt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("manvt");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaykiemtra");

                    b.Property<string>("Sothe")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sothe");

                    b.Property<string>("TenLaiXe")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tenlaixe");

                    b.Property<string>("TenNhaThau")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tennhathau");

                    b.HasKey("Id");

                    b.ToTable("dailykiemtravesinhxe");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DailyKiemtravesinhxeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyKiemtravesinhxeId")
                        .HasColumnType("integer")
                        .HasColumnName("dailykiemtravesinhxeid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ghichu");

                    b.Property<bool>("KetQua")
                        .HasColumnType("boolean")
                        .HasColumnName("ketqua");

                    b.Property<int>("ParamId")
                        .HasColumnType("integer")
                        .HasColumnName("paramid");

                    b.HasKey("Id");

                    b.HasIndex("DailyKiemtravesinhxeId");

                    b.HasIndex("ParamId");

                    b.ToTable("dailykiemtravesinhxedetail");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DailyPreTripChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecklistData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checklistdata");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("MaLx")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("malx");

                    b.Property<string>("MaNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manvt");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sothe");

                    b.Property<string>("TenLx")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenlx");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennvt");

                    b.HasKey("Id");

                    b.ToTable("dailypretripchecklist");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DangTai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DaDangKyChungTu")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaDangTai")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaVeSinh")
                        .HasColumnType("boolean");

                    b.Property<int?>("KhohangId")
                        .HasColumnType("integer");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaLx")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayDangTai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DangTais");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Danhsachxetrongkho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BaoVeKiemTraTrongKho_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BaoVeKiemTra_PreTrip_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BaoVeKiemTra_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GioDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KhohangId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KiemTraVeSinh_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LyDoVaoKho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaNhanVienLaiXe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Pre_Tripchecklist_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenLaiXe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNhaThauVanTai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThuKhoXacNhan_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("XacNhanRaCong_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("XacNhanVaoCong_Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Danhsachxetrongkhos");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Khohang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("khohang");
                });

            modelBuilder.Entity("SaleManagerApi.Models.KiemtravesinhxeParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("chitiet");

                    b.Property<bool>("DapAnDat")
                        .HasColumnType("boolean")
                        .HasColumnName("dapandat");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ghichu");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("noidung");

                    b.Property<int>("Stt")
                        .HasColumnType("integer")
                        .HasColumnName("stt");

                    b.HasKey("Id");

                    b.ToTable("kiemtravesinhxeparam");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Layoutkho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BorderRadius")
                        .HasColumnType("double precision")
                        .HasColumnName("border_radius");

                    b.Property<string>("Cot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cot");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_type");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hang");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<int>("KhohangId")
                        .HasColumnType("integer")
                        .HasColumnName("khohang_id");

                    b.Property<string>("MaLocal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ma_local");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation");

                    b.Property<double>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("KhohangId");

                    b.ToTable("layoutkho");
                });

            modelBuilder.Entity("SaleManagerApi.Models.NhaVanTai", b =>
                {
                    b.Property<string>("MaNvt")
                        .HasColumnType("text")
                        .HasColumnName("manvt");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennvt");

                    b.HasKey("MaNvt");

                    b.ToTable("nhavantai");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Nhanvien", b =>
                {
                    b.Property<string>("Mnv")
                        .HasColumnType("text")
                        .HasColumnName("mnv");

                    b.Property<string>("Chucdanh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chucdanh");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("Tnv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tnv");

                    b.Property<string>("Vitri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vitri");

                    b.HasKey("Mnv");

                    b.ToTable("nhanvien");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SaleManagerApi.Models.PhatSinhSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoaiPhatSinh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SoLuongChan")
                        .HasColumnType("integer");

                    b.Property<int?>("SoLuongLe")
                        .HasColumnType("integer");

                    b.Property<string>("SoSTO")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sothe")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("phatsinhsanpham");
                });

            modelBuilder.Entity("SaleManagerApi.Models.PreTripChecklistParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DieuKien")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dieukien");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("noidung");

                    b.Property<int>("Stt")
                        .HasColumnType("integer")
                        .HasColumnName("stt");

                    b.HasKey("Id");

                    b.ToTable("pretripchecklistparam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DieuKien = "Bằng lái xe phù hợp với loại xe điều khiển và còn hạn...",
                            IsActive = true,
                            NoiDung = "Hồ sơ và Nhân viên lái xe",
                            Stt = 1
                        });
                });

            modelBuilder.Entity("SaleManagerApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop Dell XPS 15",
                            Price = 1500.00m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bàn phím cơ Keychron Q1",
                            Price = 150.00m,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("SaleManagerApi.Models.Sanphamnuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DinhLuong")
                        .HasColumnType("integer");

                    b.Property<int>("KhohangId")
                        .HasColumnType("integer");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("KhohangId");

                    b.ToTable("sanphamnuoc");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Thenhathau", b =>
                {
                    b.Property<string>("MaLx")
                        .HasColumnType("text")
                        .HasColumnName("malx");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bienso");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cccd");

                    b.Property<string>("MaNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manvt");

                    b.Property<string>("Sodt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sodt");

                    b.Property<string>("Sothe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sothe");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten");

                    b.Property<string>("TenNvt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennvt");

                    b.Property<DateTime>("Thoihanthe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoihanthe");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer")
                        .HasColumnName("trangthai");

                    b.HasKey("MaLx");

                    b.ToTable("thenhathau");
                });

            modelBuilder.Entity("SaleManagerApi.Models.TonKhoDauKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("DinhLuong")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KhohangId")
                        .HasColumnType("integer");

                    b.Property<string>("MaHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgaySanXuat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhanTramHanSuDung")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SoLuongPalletChan")
                        .HasColumnType("integer");

                    b.Property<int?>("SoThungLe")
                        .HasColumnType("integer");

                    b.Property<string>("SttDayHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ThoiDiemGhiNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Tong")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThaiDOD")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KhohangId");

                    b.ToTable("tonkhodauky");
                });

            modelBuilder.Entity("SaleManagerApi.Models.TonKhoHienTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("DinhLuong")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KhohangId")
                        .HasColumnType("integer");

                    b.Property<string>("MaHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgaySanXuat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhanTramHanSuDung")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SoLuongPalletChan")
                        .HasColumnType("integer");

                    b.Property<int?>("SoThungLe")
                        .HasColumnType("integer");

                    b.Property<string>("SttDayHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ThoiDiemGhiNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Tong")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThaiDOD")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KhohangId");

                    b.ToTable("tonkhohientai");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DailyKiemtravesinhxeDetail", b =>
                {
                    b.HasOne("SaleManagerApi.Models.DailyKiemtravesinhxe", "DailyKiemtravesinhxe")
                        .WithMany("Details")
                        .HasForeignKey("DailyKiemtravesinhxeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleManagerApi.Models.KiemtravesinhxeParam", "Param")
                        .WithMany()
                        .HasForeignKey("ParamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyKiemtravesinhxe");

                    b.Navigation("Param");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Layoutkho", b =>
                {
                    b.HasOne("SaleManagerApi.Models.Khohang", "Khohang")
                        .WithMany()
                        .HasForeignKey("KhohangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khohang");
                });

            modelBuilder.Entity("SaleManagerApi.Models.Sanphamnuoc", b =>
                {
                    b.HasOne("SaleManagerApi.Models.Khohang", "Khohang")
                        .WithMany()
                        .HasForeignKey("KhohangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khohang");
                });

            modelBuilder.Entity("SaleManagerApi.Models.TonKhoDauKy", b =>
                {
                    b.HasOne("SaleManagerApi.Models.Khohang", "Khohang")
                        .WithMany()
                        .HasForeignKey("KhohangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khohang");
                });

            modelBuilder.Entity("SaleManagerApi.Models.TonKhoHienTai", b =>
                {
                    b.HasOne("SaleManagerApi.Models.Khohang", "Khohang")
                        .WithMany()
                        .HasForeignKey("KhohangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khohang");
                });

            modelBuilder.Entity("SaleManagerApi.Models.DailyKiemtravesinhxe", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
